spring:
  application:
    name: demo
  profiles:
    active: local
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/lyu_mysql
      username: *
      password: *

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000

#mybati自动生成代码
mybatis:
  #映射路径
  mapper-locations: classpath:mapper/*.xml
  #sql对应的实体
  type-aliases-package: com.lyu.point.demo.entity
