package com.lyu.point.demo.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class GoodsStock implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_stock.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_stock.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_stock.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_stock.stock
     *
     * @mbggenerated
     */
    private Long stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_stock.id
     *
     * @return the value of t_goods_stock.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_stock.id
     *
     * @param id the value for t_goods_stock.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_stock.name
     *
     * @return the value of t_goods_stock.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_stock.name
     *
     * @param name the value for t_goods_stock.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_stock.price
     *
     * @return the value of t_goods_stock.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_stock.price
     *
     * @param price the value for t_goods_stock.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_stock.stock
     *
     * @return the value of t_goods_stock.stock
     *
     * @mbggenerated
     */
    public Long getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_stock.stock
     *
     * @param stock the value for t_goods_stock.stock
     *
     * @mbggenerated
     */
    public void setStock(Long stock) {
        this.stock = stock;
    }
}