package com.lyu.point.demo.dao;

import com.lyu.point.demo.entity.GoodsStock;

import java.util.List;

public interface GoodsStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated
     */
    int insert(GoodsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated
     */
    int insertSelective(GoodsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated
     */
    GoodsStock selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_stock
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsStock record);

    List<GoodsStock> selectAll();
}