package com.lyu.point.demo.dao;

import com.lyu.point.demo.entity.OrderList;

public interface OrderListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_list
     *
     * @mbggenerated
     */
    int insert(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_list
     *
     * @mbggenerated
     */
    int insertSelective(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_list
     *
     * @mbggenerated
     */
    OrderList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderList record);

    /**
     * 条件查询
     * @param order
     * @return
     */
    OrderList selectByWhere(OrderList order);
}